const games = {
  // game1: '[{"row":0,"column":0,"value":5},{"row":0,"column":5,"value":7},{"row":0,"column":6,"value":6},{"row":0,"column":7,"value":4},{"row":1,"column":3,"value":4},{"row":1,"column":6,"value":1},{"row":1,"column":8,"value":2},{"row":2,"column":1,"value":9},{"row":2,"column":4,"value":1},{"row":2,"column":6,"value":7},{"row":3,"column":1,"value":8},{"row":3,"column":2,"value":7},{"row":3,"column":4,"value":2},{"row":3,"column":6,"value":5},{"row":3,"column":7,"value":1},{"row":3,"column":8,"value":6},{"row":4,"column":1,"value":3},{"row":4,"column":2,"value":5},{"row":4,"column":3,"value":8},{"row":4,"column":4,"value":6},{"row":4,"column":7,"value":7},{"row":4,"column":8,"value":9},{"row":5,"column":0,"value":6},{"row":5,"column":4,"value":7},{"row":5,"column":5,"value":1},{"row":5,"column":6,"value":8},{"row":5,"column":7,"value":3},{"row":5,"column":8,"value":4},{"row":6,"column":0,"value":2},{"row":6,"column":2,"value":6},{"row":6,"column":4,"value":9},{"row":6,"column":5,"value":3},{"row":6,"column":6,"value":4},{"row":6,"column":7,"value":5},{"row":6,"column":8,"value":8},{"row":7,"column":0,"value":9},{"row":7,"column":1,"value":4},{"row":7,"column":2,"value":1},{"row":7,"column":3,"value":2},{"row":7,"column":4,"value":5},{"row":7,"column":5,"value":8},{"row":8,"column":0,"value":8},{"row":8,"column":2,"value":3},{"row":8,"column":3,"value":7},{"row":8,"column":6,"value":9},{"row":8,"column":7,"value":2}]',

  // game2: '[{"row":0,"column":0,"value":4},{"row":0,"column":1,"value":8},{"row":0,"column":5,"value":2},{"row":0,"column":8,"value":3},{"row":1,"column":1,"value":1},{"row":1,"column":2,"value":9},{"row":1,"column":3,"value":3},{"row":1,"column":6,"value":4},{"row":1,"column":7,"value":5},{"row":1,"column":8,"value":6},{"row":2,"column":1,"value":3},{"row":2,"column":7,"value":9},{"row":3,"column":0,"value":8},{"row":3,"column":4,"value":5},{"row":3,"column":7,"value":3},{"row":4,"column":3,"value":8},{"row":4,"column":5,"value":1},{"row":5,"column":1,"value":4},{"row":5,"column":4,"value":7},{"row":5,"column":8,"value":1},{"row":6,"column":1,"value":6},{"row":6,"column":7,"value":2},{"row":7,"column":0,"value":5},{"row":7,"column":1,"value":2},{"row":7,"column":2,"value":4},{"row":7,"column":5,"value":9},{"row":7,"column":6,"value":3},{"row":7,"column":7,"value":6},{"row":8,"column":0,"value":3},{"row":8,"column":3,"value":2},{"row":8,"column":7,"value":7},{"row":8,"column":8,"value":5}]',

  // game3: '[{"row":0,"column":0,"value":5},{"row":0,"column":2,"value":2},{"row":0,"column":3,"value":7},{"row":0,"column":6,"value":3},{"row":0,"column":8,"value":8},{"row":1,"column":2,"value":6},{"row":1,"column":4,"value":9},{"row":1,"column":6,"value":7},{"row":2,"column":0,"value":3},{"row":2,"column":1,"value":8},{"row":2,"column":3,"value":5},{"row":2,"column":4,"value":2},{"row":2,"column":7,"value":1},{"row":2,"column":8,"value":9},{"row":3,"column":4,"value":8},{"row":3,"column":6,"value":5},{"row":3,"column":8,"value":1},{"row":4,"column":1,"value":6},{"row":4,"column":2,"value":1},{"row":4,"column":3,"value":4},{"row":4,"column":5,"value":5},{"row":4,"column":6,"value":2},{"row":4,"column":7,"value":8},{"row":5,"column":0,"value":4},{"row":5,"column":2,"value":8},{"row":5,"column":4,"value":7},{"row":6,"column":0,"value":6},{"row":6,"column":1,"value":7},{"row":6,"column":4,"value":4},{"row":6,"column":5,"value":3},{"row":6,"column":7,"value":5},{"row":6,"column":8,"value":2},{"row":7,"column":2,"value":4},{"row":7,"column":4,"value":5},{"row":7,"column":6,"value":1},{"row":8,"column":0,"value":2},{"row":8,"column":2,"value":5},{"row":8,"column":5,"value":7},{"row":8,"column":6,"value":9},{"row":8,"column":8,"value":4}]',

  // game4: '[{"row":0,"column":0,"value":1},{"row":0,"column":5,"value":5},{"row":0,"column":6,"value":6},{"row":1,"column":0,"value":7},{"row":1,"column":3,"value":1},{"row":1,"column":4,"value":2},{"row":1,"column":5,"value":6},{"row":1,"column":7,"value":3},{"row":2,"column":2,"value":3},{"row":2,"column":7,"value":1},{"row":2,"column":8,"value":2},{"row":3,"column":2,"value":9},{"row":3,"column":3,"value":2},{"row":3,"column":5,"value":4},{"row":3,"column":7,"value":7},{"row":4,"column":2,"value":6},{"row":4,"column":6,"value":8},{"row":5,"column":1,"value":7},{"row":5,"column":3,"value":8},{"row":5,"column":5,"value":1},{"row":5,"column":6,"value":2},{"row":6,"column":0,"value":4},{"row":6,"column":1,"value":6},{"row":6,"column":6,"value":5},{"row":7,"column":1,"value":3},{"row":7,"column":3,"value":5},{"row":7,"column":4,"value":1},{"row":7,"column":5,"value":9},{"row":7,"column":8,"value":6},{"row":8,"column":2,"value":5},{"row":8,"column":3,"value":6},{"row":8,"column":8,"value":1}]',

  // game5: '[{"row":0,"column":1,"value":3},{"row":0,"column":2,"value":7},{"row":0,"column":5,"value":5},{"row":0,"column":7,"value":4},{"row":1,"column":0,"value":4},{"row":1,"column":2,"value":5},{"row":1,"column":3,"value":2},{"row":1,"column":4,"value":7},{"row":1,"column":5,"value":1},{"row":1,"column":8,"value":8},{"row":2,"column":7,"value":7},{"row":2,"column":8,"value":1},{"row":3,"column":0,"value":5},{"row":3,"column":1,"value":2},{"row":3,"column":7,"value":1},{"row":4,"column":1,"value":9},{"row":4,"column":7,"value":2},{"row":5,"column":1,"value":7},{"row":5,"column":7,"value":9},{"row":5,"column":8,"value":4},{"row":6,"column":0,"value":7},{"row":6,"column":1,"value":4},{"row":7,"column":0,"value":8},{"row":7,"column":3,"value":6},{"row":7,"column":4,"value":4},{"row":7,"column":5,"value":3},{"row":7,"column":6,"value":7},{"row":7,"column":8,"value":9},{"row":8,"column":1,"value":5},{"row":8,"column":3,"value":8},{"row":8,"column":6,"value":4},{"row":8,"column":7,"value":6}]',

  // game6: '[{"row":0,"column":2,"value":6},{"row":0,"column":4,"value":4},{"row":0,"column":6,"value":8},{"row":0,"column":8,"value":3},{"row":1,"column":3,"value":6},{"row":1,"column":4,"value":8},{"row":1,"column":5,"value":5},{"row":2,"column":0,"value":1},{"row":2,"column":2,"value":5},{"row":2,"column":6,"value":6},{"row":3,"column":1,"value":5},{"row":3,"column":5,"value":9},{"row":3,"column":7,"value":6},{"row":4,"column":1,"value":9},{"row":4,"column":3,"value":3},{"row":4,"column":5,"value":2},{"row":4,"column":7,"value":7},{"row":5,"column":1,"value":1},{"row":5,"column":3,"value":8},{"row":5,"column":7,"value":3},{"row":6,"column":2,"value":1},{"row":6,"column":6,"value":7},{"row":6,"column":8,"value":2},{"row":7,"column":3,"value":5},{"row":7,"column":4,"value":1},{"row":7,"column":5,"value":7},{"row":8,"column":0,"value":9},{"row":8,"column":2,"value":7},{"row":8,"column":4,"value":3},{"row":8,"column":6,"value":5}]',

  // game7: '[{"row":0,"column":0,"value":3},{"row":0,"column":1,"value":2},{"row":0,"column":4,"value":4},{"row":0,"column":5,"value":5},{"row":0,"column":6,"value":9},{"row":1,"column":0,"value":9},{"row":1,"column":2,"value":7},{"row":1,"column":3,"value":6},{"row":1,"column":4,"value":3},{"row":1,"column":6,"value":2},{"row":1,"column":8,"value":5},{"row":2,"column":1,"value":5},{"row":2,"column":2,"value":1},{"row":2,"column":3,"value":9},{"row":2,"column":6,"value":6},{"row":3,"column":0,"value":2},{"row":3,"column":7,"value":4},{"row":3,"column":8,"value":9},{"row":4,"column":0,"value":7},{"row":4,"column":1,"value":6},{"row":4,"column":7,"value":5},{"row":4,"column":8,"value":8},{"row":5,"column":0,"value":5},{"row":5,"column":1,"value":9},{"row":5,"column":8,"value":6},{"row":6,"column":2,"value":5},{"row":6,"column":5,"value":4},{"row":6,"column":6,"value":8},{"row":6,"column":7,"value":6},{"row":7,"column":0,"value":6},{"row":7,"column":2,"value":2},{"row":7,"column":4,"value":5},{"row":7,"column":5,"value":7},{"row":7,"column":6,"value":4},{"row":7,"column":8,"value":3},{"row":8,"column":2,"value":9},{"row":8,"column":3,"value":3},{"row":8,"column":4,"value":8},{"row":8,"column":7,"value":1},{"row":8,"column":8,"value":2}]',

  // game8: '[{"row":0,"column":0,"value":6},{"row":0,"column":1,"value":5},{"row":0,"column":2,"value":2},{"row":0,"column":3,"value":1},{"row":0,"column":8,"value":3},{"row":1,"column":1,"value":8},{"row":1,"column":4,"value":5},{"row":1,"column":6,"value":2},{"row":1,"column":7,"value":6},{"row":1,"column":8,"value":7},{"row":2,"column":1,"value":9},{"row":2,"column":4,"value":3},{"row":2,"column":5,"value":6},{"row":2,"column":8,"value":5},{"row":3,"column":2,"value":3},{"row":3,"column":3,"value":5},{"row":3,"column":5,"value":9},{"row":3,"column":8,"value":8},{"row":4,"column":1,"value":6},{"row":4,"column":2,"value":9},{"row":4,"column":4,"value":2},{"row":4,"column":6,"value":3},{"row":4,"column":7,"value":7},{"row":5,"column":0,"value":1},{"row":5,"column":3,"value":3},{"row":5,"column":5,"value":7},{"row":5,"column":6,"value":5},{"row":6,"column":0,"value":2},{"row":6,"column":3,"value":7},{"row":6,"column":4,"value":8},{"row":6,"column":7,"value":4},{"row":7,"column":0,"value":8},{"row":7,"column":1,"value":3},{"row":7,"column":2,"value":6},{"row":7,"column":4,"value":9},{"row":7,"column":7,"value":5},{"row":8,"column":0,"value":9},{"row":8,"column":5,"value":5},{"row":8,"column":6,"value":8},{"row":8,"column":7,"value":3},{"row":8,"column":8,"value":2}]',

  // game9: '[{"row":0,"column":3,"value":4},{"row":0,"column":4,"value":2},{"row":0,"column":5,"value":5},{"row":1,"column":0,"value":4},{"row":1,"column":1,"value":1},{"row":1,"column":2,"value":2},{"row":1,"column":6,"value":5},{"row":1,"column":7,"value":8},{"row":1,"column":8,"value":7},{"row":2,"column":2,"value":5},{"row":2,"column":3,"value":7},{"row":2,"column":5,"value":8},{"row":2,"column":6,"value":6},{"row":3,"column":0,"value":3},{"row":3,"column":1,"value":9},{"row":3,"column":4,"value":6},{"row":3,"column":7,"value":5},{"row":3,"column":8,"value":4},{"row":4,"column":0,"value":1},{"row":4,"column":1,"value":6},{"row":4,"column":7,"value":9},{"row":4,"column":8,"value":3},{"row":5,"column":0,"value":5},{"row":5,"column":1,"value":2},{"row":5,"column":4,"value":7},{"row":5,"column":7,"value":1},{"row":5,"column":8,"value":6},{"row":6,"column":2,"value":3},{"row":6,"column":3,"value":6},{"row":6,"column":5,"value":4},{"row":6,"column":6,"value":1},{"row":7,"column":0,"value":7},{"row":7,"column":1,"value":8},{"row":7,"column":2,"value":1},{"row":7,"column":6,"value":4},{"row":7,"column":7,"value":6},{"row":7,"column":8,"value":9},{"row":8,"column":3,"value":1},{"row":8,"column":4,"value":8},{"row":8,"column":5,"value":7}]',


  // game10: '[{"row":0,"column":2,"value":9},{"row":0,"column":4,"value":5},{"row":0,"column":6,"value":1},{"row":1,"column":2,"value":8},{"row":1,"column":4,"value":4},{"row":1,"column":6,"value":6},{"row":2,"column":2,"value":7},{"row":2,"column":4,"value":1},{"row":2,"column":6,"value":2},{"row":3,"column":0,"value":5},{"row":3,"column":3,"value":8},{"row":3,"column":5,"value":4},{"row":3,"column":8,"value":2},{"row":4,"column":1,"value":1},{"row":4,"column":7,"value":4},{"row":5,"column":0,"value":9},{"row":5,"column":3,"value":6},{"row":5,"column":5,"value":1},{"row":5,"column":8,"value":5},{"row":6,"column":1,"value":9},{"row":6,"column":2,"value":4},{"row":6,"column":6,"value":5},{"row":6,"column":7,"value":2},{"row":7,"column":1,"value":3},{"row":7,"column":7,"value":9},{"row":8,"column":3,"value":5},{"row":8,"column":5,"value":7}]',

  // game11: '[{"row":0,"column":0,"value":6},{"row":0,"column":2,"value":5},{"row":0,"column":3,"value":9},{"row":1,"column":1,"value":8},{"row":1,"column":4,"value":3},{"row":1,"column":5,"value":7},{"row":1,"column":6,"value":5},{"row":2,"column":6,"value":8},{"row":2,"column":7,"value":6},{"row":3,"column":1,"value":7},{"row":3,"column":8,"value":8},{"row":4,"column":2,"value":2},{"row":4,"column":4,"value":5},{"row":4,"column":6,"value":3},{"row":5,"column":0,"value":4},{"row":5,"column":7,"value":5},{"row":6,"column":1,"value":5},{"row":6,"column":2,"value":6},{"row":7,"column":2,"value":9},{"row":7,"column":3,"value":4},{"row":7,"column":4,"value":2},{"row":7,"column":7,"value":3},{"row":8,"column":5,"value":9},{"row":8,"column":6,"value":1},{"row":8,"column":8,"value":2}]',

  game12: '[{"row":0,"column":4,"value":6},{"row":0,"column":6,"value":4},{"row":1,"column":1,"value":2},{"row":1,"column":4,"value":5},{"row":1,"column":5,"value":1},{"row":2,"column":1,"value":9},{"row":2,"column":6,"value":6},{"row":2,"column":8,"value":7},{"row":3,"column":0,"value":7},{"row":3,"column":2,"value":5},{"row":3,"column":6,"value":9},{"row":4,"column":3,"value":2},{"row":4,"column":5,"value":4},{"row":5,"column":2,"value":2},{"row":5,"column":6,"value":3},{"row":5,"column":8,"value":6},{"row":6,"column":0,"value":1},{"row":6,"column":2,"value":9},{"row":6,"column":7,"value":5},{"row":7,"column":3,"value":9},{"row":7,"column":4,"value":1},{"row":7,"column":7,"value":3},{"row":8,"column":2,"value":8},{"row":8,"column":4,"value":7}]',
}

const getGame = () => {
  const game = games[Object.keys(games)[Math.floor(Math.random() * Object.keys(games).length)]];
  return JSON.parse(game);
};

export { getGame }
